apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezl-backendpy-depl
  labels:
    app: ezl-backendpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezl-backendpy
  template:
    metadata:
      labels:
        app: ezl-backendpy
    spec:
      containers:
      - name: ezl-backendpy
        image: backendpy:{{FASTAPING_VERSION}}
        ports:
        - containerPort: 8000
        env:
        - name: FASTAPING_ENV
          value: prod
        - name: FASTAPING_VERSION  
          valueFrom:
            configMapKeyRef:
              name: fastaping-config
              key: FASTAPING_VERSION

---
apiVersion: v1
kind: Service
metadata:
  name: ezl-backendpy-svc
spec:
  type: NodePort
  selector:
    app: ezl-backendpy
  ports:
  - protocol: TCP
    port: 8101
    targetPort: 8000
    nodePort: 31101
