apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-depl
  labels:
    app: mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-depl
  template:
    metadata:
      labels:
        app: mongodb-depl
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  type: ClusterIP
  selector:
    app: mongodb-depl
  ports:
    - protocol: TCP
      port: 27017


